# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\x12\x08training\"\"\n\rWorkerRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"e\n\rStartResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x12\x13\n\x0breport_step\x18\x04 \x01(\x05\x12\x14\n\x0cworker_index\x18\x05 \x01(\x05\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"o\n\nMetricData\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\x05\x12\x0c\n\x04loss\x18\x04 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"\"\n\rFinishRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"1\n\rWeightRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\"b\n\x0bWeightChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\x12\x11\n\tworker_id\x18\x04 \x01(\t\x12\x0c\n\x04step\x18\x05 \x01(\x05\"Z\n\x11RebalanceResponse\x12\x12\n\nrebalanced\x18\x01 \x01(\x08\x12\r\n\x05pause\x18\x02 \x01(\x08\x12\x11\n\tnew_start\x18\x03 \x01(\x05\x12\x0f\n\x07new_end\x18\x04 \x01(\x05\x32\xd2\x03\n\x0fTrainingService\x12\x42\n\x0eRegisterWorker\x12\x17.training.WorkerRequest\x1a\x17.training.StartResponse\x12\x45\n\x11GetInitialWeights\x12\x17.training.WeightRequest\x1a\x15.training.WeightChunk0\x01\x12\x35\n\x0bPushWeights\x12\x15.training.WeightChunk\x1a\r.training.Ack(\x01\x12\x45\n\x11GetUpdatedWeights\x12\x17.training.WeightRequest\x1a\x15.training.WeightChunk0\x01\x12\x34\n\rReportMetrics\x12\x14.training.MetricData\x1a\r.training.Ack\x12\x38\n\x0e\x46inishTraining\x12\x17.training.FinishRequest\x1a\r.training.Ack\x12\x46\n\x0e\x43heckRebalance\x12\x17.training.WorkerRequest\x1a\x1b.training.RebalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERREQUEST']._serialized_start=28
  _globals['_WORKERREQUEST']._serialized_end=62
  _globals['_STARTRESPONSE']._serialized_start=64
  _globals['_STARTRESPONSE']._serialized_end=165
  _globals['_ACK']._serialized_start=167
  _globals['_ACK']._serialized_end=206
  _globals['_METRICDATA']._serialized_start=208
  _globals['_METRICDATA']._serialized_end=319
  _globals['_FINISHREQUEST']._serialized_start=321
  _globals['_FINISHREQUEST']._serialized_end=355
  _globals['_WEIGHTREQUEST']._serialized_start=357
  _globals['_WEIGHTREQUEST']._serialized_end=406
  _globals['_WEIGHTCHUNK']._serialized_start=408
  _globals['_WEIGHTCHUNK']._serialized_end=506
  _globals['_REBALANCERESPONSE']._serialized_start=508
  _globals['_REBALANCERESPONSE']._serialized_end=598
  _globals['_TRAININGSERVICE']._serialized_start=601
  _globals['_TRAININGSERVICE']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
