# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import training_pb2 as training__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/training.TrainingService/RegisterWorker',
                request_serializer=training__pb2.StartRequest.SerializeToString,
                response_deserializer=training__pb2.StartResponse.FromString,
                _registered_method=True)
        self.GetInitialWeights = channel.unary_unary(
                '/training.TrainingService/GetInitialWeights',
                request_serializer=training__pb2.WeightRequest.SerializeToString,
                response_deserializer=training__pb2.WeightResponse.FromString,
                _registered_method=True)
        self.PushGradients = channel.unary_unary(
                '/training.TrainingService/PushGradients',
                request_serializer=training__pb2.GradientData.SerializeToString,
                response_deserializer=training__pb2.Ack.FromString,
                _registered_method=True)
        self.GetUpdatedWeights = channel.unary_unary(
                '/training.TrainingService/GetUpdatedWeights',
                request_serializer=training__pb2.WeightRequest.SerializeToString,
                response_deserializer=training__pb2.WeightResponse.FromString,
                _registered_method=True)
        self.ReportMetrics = channel.unary_unary(
                '/training.TrainingService/ReportMetrics',
                request_serializer=training__pb2.MetricData.SerializeToString,
                response_deserializer=training__pb2.Ack.FromString,
                _registered_method=True)
        self.FinishTraining = channel.unary_unary(
                '/training.TrainingService/FinishTraining',
                request_serializer=training__pb2.FinishRequest.SerializeToString,
                response_deserializer=training__pb2.Ack.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInitialWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpdatedWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=training__pb2.StartRequest.FromString,
                    response_serializer=training__pb2.StartResponse.SerializeToString,
            ),
            'GetInitialWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInitialWeights,
                    request_deserializer=training__pb2.WeightRequest.FromString,
                    response_serializer=training__pb2.WeightResponse.SerializeToString,
            ),
            'PushGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.PushGradients,
                    request_deserializer=training__pb2.GradientData.FromString,
                    response_serializer=training__pb2.Ack.SerializeToString,
            ),
            'GetUpdatedWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdatedWeights,
                    request_deserializer=training__pb2.WeightRequest.FromString,
                    response_serializer=training__pb2.WeightResponse.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=training__pb2.MetricData.FromString,
                    response_serializer=training__pb2.Ack.SerializeToString,
            ),
            'FinishTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishTraining,
                    request_deserializer=training__pb2.FinishRequest.FromString,
                    response_serializer=training__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'training.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('training.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/RegisterWorker',
            training__pb2.StartRequest.SerializeToString,
            training__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInitialWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/GetInitialWeights',
            training__pb2.WeightRequest.SerializeToString,
            training__pb2.WeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/PushGradients',
            training__pb2.GradientData.SerializeToString,
            training__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpdatedWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/GetUpdatedWeights',
            training__pb2.WeightRequest.SerializeToString,
            training__pb2.WeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/ReportMetrics',
            training__pb2.MetricData.SerializeToString,
            training__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.TrainingService/FinishTraining',
            training__pb2.FinishRequest.SerializeToString,
            training__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
