# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated_grad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated_grad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x65\x64\x65rated_grad.proto\x12\rfederated_sum\"@\n\x0cTrainRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0e\n\x06labels\x18\x02 \x03(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"\xa9\x01\n\rTrainResponse\x12>\n\tgradients\x18\x01 \x03(\x0b\x32+.federated_sum.TrainResponse.GradientsEntry\x12\x0c\n\x04loss\x18\x02 \x01(\x01\x1aJ\n\x0eGradientsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.federated_sum.Gradients:\x02\x38\x01\"*\n\tGradients\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"\x93\x01\n\rWeightRequest\x12:\n\x07weights\x18\x01 \x03(\x0b\x32).federated_sum.WeightRequest.WeightsEntry\x1a\x46\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.federated_sum.Weights:\x02\x38\x01\"(\n\x07Weights\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"\x1c\n\tWeightAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9a\x01\n\x06Worker\x12G\n\nTrainBatch\x12\x1b.federated_sum.TrainRequest\x1a\x1c.federated_sum.TrainResponse\x12G\n\rUpdateWeights\x12\x1c.federated_sum.WeightRequest\x1a\x18.federated_sum.WeightAckB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_grad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_TRAINRESPONSE_GRADIENTSENTRY']._loaded_options = None
  _globals['_TRAINRESPONSE_GRADIENTSENTRY']._serialized_options = b'8\001'
  _globals['_WEIGHTREQUEST_WEIGHTSENTRY']._loaded_options = None
  _globals['_WEIGHTREQUEST_WEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=39
  _globals['_TRAINREQUEST']._serialized_end=103
  _globals['_TRAINRESPONSE']._serialized_start=106
  _globals['_TRAINRESPONSE']._serialized_end=275
  _globals['_TRAINRESPONSE_GRADIENTSENTRY']._serialized_start=201
  _globals['_TRAINRESPONSE_GRADIENTSENTRY']._serialized_end=275
  _globals['_GRADIENTS']._serialized_start=277
  _globals['_GRADIENTS']._serialized_end=319
  _globals['_WEIGHTREQUEST']._serialized_start=322
  _globals['_WEIGHTREQUEST']._serialized_end=469
  _globals['_WEIGHTREQUEST_WEIGHTSENTRY']._serialized_start=399
  _globals['_WEIGHTREQUEST_WEIGHTSENTRY']._serialized_end=469
  _globals['_WEIGHTS']._serialized_start=471
  _globals['_WEIGHTS']._serialized_end=511
  _globals['_WEIGHTACK']._serialized_start=513
  _globals['_WEIGHTACK']._serialized_end=541
  _globals['_WORKER']._serialized_start=544
  _globals['_WORKER']._serialized_end=698
# @@protoc_insertion_point(module_scope)
