// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: federated_sum.proto

package federated_sum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_federated_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_federated_sum_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type SumReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumReply) Reset() {
	*x = SumReply{}
	mi := &file_federated_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumReply) ProtoMessage() {}

func (x *SumReply) ProtoReflect() protoreflect.Message {
	mi := &file_federated_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumReply.ProtoReflect.Descriptor instead.
func (*SumReply) Descriptor() ([]byte, []int) {
	return file_federated_sum_proto_rawDescGZIP(), []int{1}
}

func (x *SumReply) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_federated_sum_proto protoreflect.FileDescriptor

const file_federated_sum_proto_rawDesc = "" +
	"\n" +
	"\x13federated_sum.proto\x12\x05inter\"&\n" +
	"\n" +
	"SumRequest\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\"\"\n" +
	"\bSumReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2=\n" +
	"\tProcessor\x120\n" +
	"\n" +
	"ComputeSum\x12\x11.inter.SumRequest\x1a\x0f.inter.SumReplyB\x11Z\x0f./federated_sumb\x06proto3"

var (
	file_federated_sum_proto_rawDescOnce sync.Once
	file_federated_sum_proto_rawDescData []byte
)

func file_federated_sum_proto_rawDescGZIP() []byte {
	file_federated_sum_proto_rawDescOnce.Do(func() {
		file_federated_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_sum_proto_rawDesc), len(file_federated_sum_proto_rawDesc)))
	})
	return file_federated_sum_proto_rawDescData
}

var file_federated_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_federated_sum_proto_goTypes = []any{
	(*SumRequest)(nil), // 0: inter.SumRequest
	(*SumReply)(nil),   // 1: inter.SumReply
}
var file_federated_sum_proto_depIdxs = []int32{
	0, // 0: inter.Processor.ComputeSum:input_type -> inter.SumRequest
	1, // 1: inter.Processor.ComputeSum:output_type -> inter.SumReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_federated_sum_proto_init() }
func file_federated_sum_proto_init() {
	if File_federated_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_sum_proto_rawDesc), len(file_federated_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federated_sum_proto_goTypes,
		DependencyIndexes: file_federated_sum_proto_depIdxs,
		MessageInfos:      file_federated_sum_proto_msgTypes,
	}.Build()
	File_federated_sum_proto = out.File
	file_federated_sum_proto_goTypes = nil
	file_federated_sum_proto_depIdxs = nil
}
