// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: federated_grad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []float32              `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Labels        []int32                `protobuf:"varint,2,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_federated_grad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRequest) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrainRequest) GetLabels() []int32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TrainRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gradients     map[string]*Gradients  `protobuf:"bytes,1,rep,name=gradients,proto3" json:"gradients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Loss          float64                `protobuf:"fixed64,2,opt,name=loss,proto3" json:"loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_federated_grad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{1}
}

func (x *TrainResponse) GetGradients() map[string]*Gradients {
	if x != nil {
		return x.Gradients
	}
	return nil
}

func (x *TrainResponse) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

type Gradients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Shape         []int32                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gradients) Reset() {
	*x = Gradients{}
	mi := &file_federated_grad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gradients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gradients) ProtoMessage() {}

func (x *Gradients) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gradients.ProtoReflect.Descriptor instead.
func (*Gradients) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{2}
}

func (x *Gradients) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Gradients) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type WeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       map[string]*Weights    `protobuf:"bytes,1,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightRequest) Reset() {
	*x = WeightRequest{}
	mi := &file_federated_grad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightRequest) ProtoMessage() {}

func (x *WeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightRequest.ProtoReflect.Descriptor instead.
func (*WeightRequest) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{3}
}

func (x *WeightRequest) GetWeights() map[string]*Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

type Weights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Shape         []int32                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weights) Reset() {
	*x = Weights{}
	mi := &file_federated_grad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weights) ProtoMessage() {}

func (x *Weights) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weights.ProtoReflect.Descriptor instead.
func (*Weights) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{4}
}

func (x *Weights) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Weights) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type WeightAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightAck) Reset() {
	*x = WeightAck{}
	mi := &file_federated_grad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightAck) ProtoMessage() {}

func (x *WeightAck) ProtoReflect() protoreflect.Message {
	mi := &file_federated_grad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightAck.ProtoReflect.Descriptor instead.
func (*WeightAck) Descriptor() ([]byte, []int) {
	return file_federated_grad_proto_rawDescGZIP(), []int{5}
}

func (x *WeightAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_federated_grad_proto protoreflect.FileDescriptor

const file_federated_grad_proto_rawDesc = "" +
	"\n" +
	"\x14federated_grad.proto\x12\rfederated_sum\"Y\n" +
	"\fTrainRequest\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x02R\x04data\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\x05R\x06labels\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\"\xc6\x01\n" +
	"\rTrainResponse\x12I\n" +
	"\tgradients\x18\x01 \x03(\v2+.federated_sum.TrainResponse.GradientsEntryR\tgradients\x12\x12\n" +
	"\x04loss\x18\x02 \x01(\x01R\x04loss\x1aV\n" +
	"\x0eGradientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.federated_sum.GradientsR\x05value:\x028\x01\"9\n" +
	"\tGradients\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x05R\x05shape\"\xa8\x01\n" +
	"\rWeightRequest\x12C\n" +
	"\aweights\x18\x01 \x03(\v2).federated_sum.WeightRequest.WeightsEntryR\aweights\x1aR\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.federated_sum.WeightsR\x05value:\x028\x01\"7\n" +
	"\aWeights\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x05R\x05shape\"%\n" +
	"\tWeightAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9a\x01\n" +
	"\x06Worker\x12G\n" +
	"\n" +
	"TrainBatch\x12\x1b.federated_sum.TrainRequest\x1a\x1c.federated_sum.TrainResponse\x12G\n" +
	"\rUpdateWeights\x12\x1c.federated_sum.WeightRequest\x1a\x18.federated_sum.WeightAckB\tZ\a./protob\x06proto3"

var (
	file_federated_grad_proto_rawDescOnce sync.Once
	file_federated_grad_proto_rawDescData []byte
)

func file_federated_grad_proto_rawDescGZIP() []byte {
	file_federated_grad_proto_rawDescOnce.Do(func() {
		file_federated_grad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_grad_proto_rawDesc), len(file_federated_grad_proto_rawDesc)))
	})
	return file_federated_grad_proto_rawDescData
}

var file_federated_grad_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_federated_grad_proto_goTypes = []any{
	(*TrainRequest)(nil),  // 0: federated_sum.TrainRequest
	(*TrainResponse)(nil), // 1: federated_sum.TrainResponse
	(*Gradients)(nil),     // 2: federated_sum.Gradients
	(*WeightRequest)(nil), // 3: federated_sum.WeightRequest
	(*Weights)(nil),       // 4: federated_sum.Weights
	(*WeightAck)(nil),     // 5: federated_sum.WeightAck
	nil,                   // 6: federated_sum.TrainResponse.GradientsEntry
	nil,                   // 7: federated_sum.WeightRequest.WeightsEntry
}
var file_federated_grad_proto_depIdxs = []int32{
	6, // 0: federated_sum.TrainResponse.gradients:type_name -> federated_sum.TrainResponse.GradientsEntry
	7, // 1: federated_sum.WeightRequest.weights:type_name -> federated_sum.WeightRequest.WeightsEntry
	2, // 2: federated_sum.TrainResponse.GradientsEntry.value:type_name -> federated_sum.Gradients
	4, // 3: federated_sum.WeightRequest.WeightsEntry.value:type_name -> federated_sum.Weights
	0, // 4: federated_sum.Worker.TrainBatch:input_type -> federated_sum.TrainRequest
	3, // 5: federated_sum.Worker.UpdateWeights:input_type -> federated_sum.WeightRequest
	1, // 6: federated_sum.Worker.TrainBatch:output_type -> federated_sum.TrainResponse
	5, // 7: federated_sum.Worker.UpdateWeights:output_type -> federated_sum.WeightAck
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_federated_grad_proto_init() }
func file_federated_grad_proto_init() {
	if File_federated_grad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_grad_proto_rawDesc), len(file_federated_grad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federated_grad_proto_goTypes,
		DependencyIndexes: file_federated_grad_proto_depIdxs,
		MessageInfos:      file_federated_grad_proto_msgTypes,
	}.Build()
	File_federated_grad_proto = out.File
	file_federated_grad_proto_goTypes = nil
	file_federated_grad_proto_depIdxs = nil
}
