# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated_sum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated_sum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x65\x64\x65rated_sum.proto\x12\x05inter\"\x1d\n\nSumRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"\x1a\n\x08SumReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32=\n\tProcessor\x12\x30\n\nComputeSum\x12\x11.inter.SumRequest\x1a\x0f.inter.SumReplyB\x11Z\x0f./federated_sumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_sum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./federated_sum'
  _globals['_SUMREQUEST']._serialized_start=30
  _globals['_SUMREQUEST']._serialized_end=59
  _globals['_SUMREPLY']._serialized_start=61
  _globals['_SUMREPLY']._serialized_end=87
  _globals['_PROCESSOR']._serialized_start=89
  _globals['_PROCESSOR']._serialized_end=150
# @@protoc_insertion_point(module_scope)
