# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x08training\"\x07\n\x05\x45mpty\"!\n\x0cStartRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"3\n\rStartResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x13\n\x0breport_step\x18\x02 \x01(\x05\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x83\x01\n\nMetricData\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\x05\x12\x0c\n\x04loss\x18\x04 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x12\n\nmodel_type\x18\x07 \x01(\t\"\x8d\x01\n\x0eTrainingResult\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\x12\x12\n\nfinal_loss\x18\x03 \x01(\x02\x12\x16\n\x0e\x66inal_accuracy\x18\x04 \x01(\x02\x12\x14\n\x0ctotal_epochs\x18\x05 \x01(\x05\x12\x12\n\nmodel_path\x18\x06 \x01(\t\"4\n\x0bMetricsList\x12%\n\x07metrics\x18\x01 \x03(\x0b\x32\x14.training.MetricData2\xc9\x01\n\x0eMetricsService\x12\x34\n\rReportMetrics\x12\x14.training.MetricData\x1a\r.training.Ack\x12\x41\n\x16ReportTrainingComplete\x12\x18.training.TrainingResult\x1a\r.training.Ack\x12>\n\x0bStartSignal\x12\x16.training.StartRequest\x1a\x17.training.StartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_STARTREQUEST']._serialized_start=36
  _globals['_STARTREQUEST']._serialized_end=69
  _globals['_STARTRESPONSE']._serialized_start=71
  _globals['_STARTRESPONSE']._serialized_end=122
  _globals['_ACK']._serialized_start=124
  _globals['_ACK']._serialized_end=163
  _globals['_METRICDATA']._serialized_start=166
  _globals['_METRICDATA']._serialized_end=297
  _globals['_TRAININGRESULT']._serialized_start=300
  _globals['_TRAININGRESULT']._serialized_end=441
  _globals['_METRICSLIST']._serialized_start=443
  _globals['_METRICSLIST']._serialized_end=495
  _globals['_METRICSSERVICE']._serialized_start=498
  _globals['_METRICSSERVICE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
